#define K_W      0x0   /* W */
#define K_A      0x1   /* A */
#define K_U      0x2   /* U */
#define K_S      0x3   /* S */
#define K_C      0x4   /* C */
#define K_X      0x5   /* X */
#define K_T      0x6   /* T */
#define K_L      0x7   /* L */
#define K_r      0x8   /* r */
#define K_f      0x9   /* f */
#define K_g      0xA   /* g */
#define SQUOTE   0xB   /* ' */
#define K_w      0xC   /* w */
#define K_d      0xD   /* d */
#define K_u      0xE   /* u */
#define K_a      0xF   /* a */
#define K_o      0x10  /* o */
#define K_i      0x11  /* i */
#define K_e      0x12  /* e */
#define K_n      0x13  /* n */
#define K_t      0x14  /* t */
#define K_h      0x15  /* h */
#define K_s      0x16  /* s */
#define K_l      0x17  /* l */
#define K_c      0x18  /* c */
#define K_y      0x19  /* y */
#define K_b      0x1A  /* b */
#define K_p      0x1B  /* p */
#define PERIOD   0x1C  /* . */
#define K_m      0x1D  /* m */
#define COMMA    0x1E  /* , */
#define K_k      0x1F  /* k */
#define K_v      0x20  /* v */
#define UNDER    0x21  /* _ */
#define DQUOTE   0x22  /* " */
#define K_0      0x23  /* 0 */
#define K_1      0x24  /* 1 */
#define K_x      0x25  /* x */
#define K_5      0x26  /* 5 */
#define K_2      0x27  /* 2 */
#define K_8      0x28  /* 8 */
#define K_9      0x29  /* 9 */
#define K_3      0x2A  /* 3 */
#define K_4      0x2B  /* 4 */
#define K_z      0x2C  /* z */
#define K_j      0x2D  /* j */
#define K_6      0x2E  /* 6 */
#define K_7      0x2F  /* 7 */
#define K_q      0x30  /* q */
#define COLON    0x31  /* : */
#define RPARN    0x32  /* ) */
#define LPARN    0x33  /* ( */
#define AND      0x34  /* & */
#define QUESTN   0x35  /* ? */
#define SMICOLN  0x36  /* ; */
#define PCENT    0x37  /* % */
#define FWSLASH  0x38  /* / */
#define EQUALS   0x39  /* = */
#define MINUS    0x3A  /* - */
#define TIMES    0x3B  /* * */
#define PLUS     0x3C  /* + */
#define BLAH     0x3D  /* ¢ */
#define CAROT    0x3E  /* ^ */
#define FRANCE   0x3F  /* Ç */
#define SEEN     0x40  /* ! */
#define MONEY    0x41  /* $ */
#define LBRAK    0x42  /* [ */
#define AT       0x43  /* @ */
#define ESPNL    0x44  /* ¿ */
#define HSHTG    0x45  /* # */
#define RBRAK    0x46  /* ] */
#define EEEEE    0x47  /* é */
#define EH       0x48  /* ` */
#define HALF     0x49  /* ½ */
#define TILD     0x4A  /* ~ */
#define QURT     0x4B  /* ¼ */
#define PARA     0x4C  /* ¶ */
#define SECTN    0x4D  /* § */
#define K_K      0x4E  /* K */
#define K_F      0x4F  /* F */
#define K_Z      0x50  /* Z */
#define K_V      0x51  /* V */
#define K_E      0x52  /* E */
#define K_Y      0x53  /* Y */
#define K_Q      0x54  /* Q */
#define K_N      0x55  /* N */
#define K_P      0x56  /* P */
#define K_G      0x57  /* G */
#define K_H      0x58  /* H */
#define K_D      0x59  /* D */
#define K_B      0x5A  /* B */
#define K_J      0x5B  /* J */
#define K_R      0x5C  /* R */
#define K_O      0x5D  /* O */
#define K_M      0x5E  /* M */
#define K_I      0x5F  /* I */
#define None	 0xFF


const PROGMEM uint16_t ascii[] = { None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, SEEN, DQUOTE, HSHTG, MONEY, PCENT, AND, SQUOTE, LPARN, RPARN, TIMES, PLUS, COMMA, MINUS, PERIOD, FWSLASH, K_0, K_1, K_2, K_3, K_4, K_5, K_6, K_7, K_8, K_9, COLON, SMICOLN, None, EQUALS, None, QUESTN, AT, K_A, K_B, K_C, K_D, K_E, K_F, K_G, K_H, K_I, K_J, K_K, K_L, K_M, K_N, K_O, K_P, K_Q, K_R, K_S, K_T, K_U, K_V, K_W, K_X, K_Y, K_Z, LBRAK, None, RBRAK, CAROT, UNDER, EH, K_a, K_b, K_c, K_d, K_e, K_f, K_g, K_h, K_i, K_j, K_k, K_l, K_m, K_n, K_o, K_p, K_q, K_r, K_s, K_t, K_u, K_v, K_w, K_x, K_y, K_z, None, None, None, TILD, None };
